# DataFrame of data from Reddit

In [ ]:
import glob
import pandas as pd

pd.set_option("display.max_colwidth", 60)
MONTH, YEAR = "2016-06", 2016

# --- comments ---
files = glob.glob(rf"C:\reddit_parquet\comments\subreddit=*\year={YEAR}\RC_{MONTH}.parquet")
comments = pd.concat((pd.read_parquet(f) for f in files), ignore_index=True)
comments["created"] = pd.to_datetime(comments["created_utc"], unit="s", utc=True)

# --- submissions (posts) ---
files = glob.glob(rf"C:\reddit_parquet\submissions\subreddit=*\year={YEAR}\RS_{MONTH}.parquet")
posts = pd.concat((pd.read_parquet(f) for f in files), ignore_index=True)
posts["created"] = pd.to_datetime(posts["created_utc"], unit="s", utc=True)

print("posts:", posts.shape)
posts[["created", "subreddit", "author", "title", "score", "num_comments", "domain"]].head(10)

comments: (750651, 10)

,created,subreddit,author,title,score,num_comments,domain
0,2016-06-01 00:00:32+00:00,books,hiimpaul46,Just finished Catcher in the Rye...,17,7,self.books
1,2016-06-01 00:25:28+00:00,books,[deleted],Download strategic analytics advancing strategy executio...,1,0,filez.in
2,2016-06-01 01:18:36+00:00,books,LegooMandarinDavid,How to express your feeling in simple Chinese? Learn How...,1,1,youtube.com
3,2016-06-01 01:23:04+00:00,books,Jmanorama,Dance of Dragons (Game of Thrones) Question,18,8,self.books
4,2016-06-01 01:54:06+00:00,books,Dsand95,I'm looking for specific books of science (plus a questi...,1,0,self.books
5,2016-06-01 01:59:40+00:00,books,hiphophipp0,My ambitious summer reading list:,12,14,self.books
6,2016-06-01 02:06:26+00:00,books,MsHarboe,Author Gretchen Rubin on Mastering Habits &amp; Happines...,1,1,biography.com
7,2016-06-01 02:10:17+00:00,books,bisinglesdating,meeting more bi women and men,1,0,self.books
8,2016-06-01 02:15:39+00:00,books,luongnhat,Loa Sub Nexo 1500,1,0,proaudio.com.vn
9,2016-06-01 02:23:52+00:00,books,MTD3454,Looking for Audiobooks,1,1,self.books

In [5]:
print("comments:", comments.shape)
comments[["created", "subreddit", "author", "score", "body", "parent_id", "link_id"]].head(10)

comments: (750651, 10)

,created,subreddit,author,score,body,parent_id,link_id
0,2016-06-01 00:00:15+00:00,books,[deleted],7,Anything by Bulgakov (as you already mentioned). You ca...,t3_4ly9t4,t3_4ly9t4
1,2016-06-01 00:00:24+00:00,books,[deleted],1,[deleted],t3_4ly6cz,t3_4ly6cz
2,2016-06-01 00:00:29+00:00,books,Cenodoxus,3,I don't know that I'd necessarily gloss *Life of Pi* tha...,t1_d3qdzyy,t3_4lugqb
3,2016-06-01 00:00:31+00:00,books,chomstar,1,I read it for the first time last week and coincidentall...,t1_d3qco44,t3_4lugqb
4,2016-06-01 00:01:17+00:00,books,[deleted],1,[deleted],t1_d3r24b1,t3_4lugqb
5,2016-06-01 00:01:36+00:00,books,[deleted],1,[deleted],t1_d3qm1ef,t3_4lugqb
6,2016-06-01 00:02:08+00:00,books,ReallyRick,-1,"good lord, you're worse than the book",t1_d3qp547,t3_4lugqb
7,2016-06-01 00:02:08+00:00,books,chomstar,1,Wow yes that was a very powerful read to me.,t1_d3qbtff,t3_4lugqb
8,2016-06-01 00:02:42+00:00,books,nwfauna,2,The Brief and Wonderous Life of Oscar Wao by Junot Díaz\...,t3_4lugqb,t3_4lugqb
9,2016-06-01 00:03:51+00:00,books,[deleted],1,[removed],t3_4lugqb,t3_4lugqb