# DataFrame of data from Reddit

In [7]:
import glob
import pandas as pd

pd.set_option("display.max_colwidth", 60)
MONTH, YEAR = "2016-06", 2016

# --- comments ---
files = glob.glob(rf"C:\reddit_parquet\comments\subreddit=*\year={YEAR}\RC_{MONTH}.parquet")
comments = pd.concat((pd.read_parquet(f) for f in files), ignore_index=True)
comments["created"] = pd.to_datetime(comments["created_utc"], unit="s", utc=True)

# --- submissions (posts) ---
files = glob.glob(rf"C:\reddit_parquet\submissions\subreddit=*\year={YEAR}\RS_{MONTH}.parquet")
posts = pd.concat((pd.read_parquet(f) for f in files), ignore_index=True)
posts["created"] = pd.to_datetime(posts["created_utc"], unit="s", utc=True)

print("posts:", posts.shape)
print(posts["subreddit"].value_counts(), "\n")

(posts.sample(frac=1, random_state=8)
      .groupby("subreddit").head(2)
      .sort_values("subreddit")
      [["created", "subreddit", "author", "title", "score", "num_comments", "domain"]])

posts: (48622, 13)
subreddit
explainlikeimfive    19289
todayilearned        16153
books                 6223
teenagers             4778
memes                 2121
nosurf                  58
Name: count, dtype: int64

,created,subreddit,author,title,score,num_comments,domain
683,2016-06-04 10:15:50+00:00,books,trinhlam365,New Hội An city – Tổ hợp du lịch nghỉ dưỡng đắt giá nhất...,1,0,newhoiancity.vietnamcondotel.net
3694,2016-06-18 18:15:38+00:00,books,[deleted],[META]book nerds on reddit love being validated,1,0,dailydot.com
9178,2016-06-06 00:31:11+00:00,explainlikeimfive,SoleyBored,ELI5: Why do so many people vanish mysteriously in natio...,0,3,self.explainlikeimfive
23203,2016-06-27 02:47:19+00:00,explainlikeimfive,[deleted],Why can you feel your heart more clearly after phsyical ...,1,0,self.explainlikeimfive
25828,2016-06-04 17:13:52+00:00,memes,mbmanning,GREATEST OF ALL TIME. #RIPAli,1,0,imgur.com
26510,2016-06-14 09:35:25+00:00,memes,Tyrann0saurus_Rex,About r/the_donald,1,0,imgflip.com
27644,2016-06-05 19:48:52+00:00,nosurf,[deleted],How many men watch porn?,4,10,self.nosurf
27689,2016-06-28 14:08:14+00:00,nosurf,Kiechi,I've noticed my memory sucks compared to what it used to...,3,3,self.nosurf
28491,2016-06-05 20:03:57+00:00,teenagers,rteenagersthrowaway7,[Advice] How do I become more confident again and make b...,7,0,self.teenagers
28595,2016-06-06 04:54:39+00:00,teenagers,128keaton,[Relationship] I asked a girl out and got her number,11,2,self.teenagers
41608,2016-06-17 10:16:31+00:00,todayilearned,Xolotl123,TIL that the BBC regularly rehearses the Queen's death i...,5385,1773,mirror.co.uk
34375,2016-06-04 07:17:12+00:00,todayilearned,pvolk,"TIL ""Benjamin Bennett"" has a YouTube channel with only v...",1,0,youtu.be

In [8]:
print("comments:", comments.shape)
print(comments["subreddit"].value_counts(), "\n")

(comments.sample(frac=1, random_state=8)
         .groupby("subreddit").head(2)
         .sort_values("subreddit")
         [["created", "subreddit", "author", "score", "body", "parent_id", "link_id"]])

comments: (750651, 10)
subreddit
todayilearned        462234
explainlikeimfive    148820
books                 71825
teenagers             65492
memes                  1989
nosurf                  291
Name: count, dtype: int64

,created,subreddit,author,score,body,parent_id,link_id
17193,2016-06-08 17:35:14+00:00,books,demolpolis,4,Not to mention amazon. used books there are &lt;2$ ship...,t1_d40xz8d,t3_4n4jnb
53243,2016-06-21 16:20:17+00:00,books,patentolog1st,0,"No, they really don't listen to the public.\n\nThey don'...",t1_d4i4cy8,t3_4p1r6h
196490,2016-06-25 15:17:44+00:00,explainlikeimfive,VictorTrejo,3,But it makes sense with context. The previous post was a...,t1_d4njv7m,t3_4poj64
116897,2016-06-10 02:49:00+00:00,explainlikeimfive,slash178,2,Rape is far more common than murder.\n\nMurders of rando...,t3_4ne9yq,t3_4ne9yq
221152,2016-06-07 21:48:20+00:00,memes,Meme_Catalogue,1,Doot doot,t3_4luake,t3_4luake
221442,2016-06-12 14:07:31+00:00,memes,Do_Whatever_You_Like,1,huh?,t1_d45s8zs,t3_4nm91g
222783,2016-06-09 22:08:17+00:00,nosurf,LifeAgain,1,Thanks so much.. my strategy is just go cold turkey on q...,t1_d42py82,t3_4nc4qw
222917,2016-06-28 15:19:04+00:00,nosurf,suzyduzy,5,If by 'cold turkey' you mean cutting yourself off entire...,t3_4q9ik3,t3_4q9ik3
281378,2016-06-28 07:59:41+00:00,teenagers,DullEmber,2,"Start a staff revolution, overthrow the main office.",t1_d4qyr2w,t3_4q816d
246738,2016-06-12 15:52:38+00:00,teenagers,owetre18,1,"I have friends ranging from 13-25. I'm 16, if you can't ...",t3_4nops8,t3_4nops8
441457,2016-06-10 16:02:47+00:00,todayilearned,HCagn,16,Great episode too. Think it's This American Life - ep 56...,t1_d43okkq,t3_4ng2s1
469395,2016-06-12 14:30:55+00:00,todayilearned,[deleted],2,To make a spectacle. \n\nSPOILERS AHEAD!\n\nThere is a s...,t1_d45u4g4,t3_4np0ch